package rekisterit;
// Generated by ComTest BEGIN
import rekisterit.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import tiedot.Lautapeli;

/**
 * Test class made by ComTest
 * @version 2012.04.25 18:30:26 // Generated by ComTest
 *
 */
public class LautapelitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa93 
   * @throws OmaException when error
   */
  @Test
  public void testLisaa93() throws OmaException {    // Lautapelit: 93
    Lautapelit lautapelit = new Lautapelit(); 
    Lautapeli Caylus1 = new Lautapeli(); 
    Lautapeli Caylus2 = new Lautapeli(); 
    Lautapeli Caylus3 = new Lautapeli(); 
    Lautapeli Caylus4 = new Lautapeli(); 
    Lautapeli Caylus5 = new Lautapeli(); 
    Lautapeli Caylus6 = new Lautapeli(); 
    Caylus1.rekisteroi(); 
    Caylus2.rekisteroi(); 
    Caylus3.rekisteroi(); 
    Caylus4.rekisteroi(); 
    Caylus5.rekisteroi(); 
    Caylus6.rekisteroi(); 
    Caylus1.vastaaPeli(); 
    Caylus2.vastaaPeli(); 
    Caylus3.vastaaPeli(); 
    Caylus4.vastaaPeli(); 
    Caylus5.vastaaPeli(); 
    Caylus6.vastaaPeli(); 
    assertEquals("From: Lautapelit line: 115", 0, lautapelit.getLukumaara()); 
    lautapelit.lisaa(Caylus1); assertEquals("From: Lautapelit line: 116", 1, lautapelit.getLukumaara()); 
    lautapelit.lisaa(Caylus2); assertEquals("From: Lautapelit line: 117", 2, lautapelit.getLukumaara()); 
    try {
    lautapelit.lisaa(Caylus1); 
    fail("Lautapelit: 118 Did not throw OmaException");
    } catch(OmaException _e_){ _e_.getMessage(); }
    assertEquals("From: Lautapelit line: 119", Caylus1, lautapelit.anna(1)); 
    assertEquals("From: Lautapelit line: 120", Caylus2, lautapelit.anna(2)); 
    lautapelit.lisaa(Caylus3); 
    lautapelit.lisaa(Caylus4); 
    lautapelit.lisaa(Caylus6); 
    try {
    lautapelit.lisaa(Caylus6); 
    fail("Lautapelit: 124 Did not throw OmaException");
    } catch(OmaException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}