package rekisterit;
// Generated by ComTest BEGIN
import rekisterit.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import tiedot.Pelaaja;
/**
 * Test class made by ComTest
 * @version 2012.04.15 20:50:13 // Generated by ComTest
 *
 */
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa45 
   * @throws OmaException when error
   */
  @Test
  public void testLisaa45() throws OmaException {    // Pelaajat: 45
    Pelaajat Pelaajat = new Pelaajat(); 
    Pelaaja Pelaaja1 = new Pelaaja(); 
    Pelaaja Pelaaja2 = new Pelaaja(); 
    Pelaaja Pelaaja3 = new Pelaaja(); 
    Pelaaja1.rekisteroi(); 
    Pelaaja2.rekisteroi(); 
    Pelaaja3.rekisteroi(); 
    Pelaaja1.vastaaPelaaja(); 
    Pelaaja2.vastaaPelaaja(); 
    assertEquals("From: Pelaajat line: 57", 0, Pelaajat.getLukumaara()); 
    Pelaajat.lisaa(Pelaaja1); assertEquals("From: Pelaajat line: 58", 1, Pelaajat.getLukumaara()); 
    Pelaajat.lisaa(Pelaaja2); assertEquals("From: Pelaajat line: 59", 2, Pelaajat.getLukumaara()); 
    try {
    Pelaajat.lisaa(Pelaaja1); 
    fail("Pelaajat: 60 Did not throw OmaException");
    } catch(OmaException _e_){ _e_.getMessage(); }
    assertEquals("From: Pelaajat line: 61", Pelaaja1, Pelaajat.anna(1)); 
    assertEquals("From: Pelaajat line: 62", Pelaaja2, Pelaajat.anna(2)); 
  } // Generated by ComTest END
}