package rekisterit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisterit.*;
// Generated by ComTest END
import tiedot.Lautapeli;
import tiedot.Pelaaja;
import tiedot.PelaajanPeli;

/**
 * Test class made by ComTest
 * @version 2012.04.02 15:19:37 // Generated by ComTest
 *
 */
public class PelaajanPelitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa36 
   * @throws OmaException when error
   */
  @Test
  public void testLisaa36() throws OmaException {    // PelaajanPelit: 36
    PelaajanPelit pelaajanPelit = new PelaajanPelit(); 
    Pelaaja pate = new Pelaaja(); 
    Lautapeli peli = new Lautapeli(); 
    Lautapeli peli2 = new Lautapeli(); 
    pate.rekisteroi(); 
    peli.rekisteroi(); 
    peli2.rekisteroi(); 
    pelaajanPelit.lisaa(1,1); 
    pelaajanPelit.lisaa(1,2); 
    try {
    pelaajanPelit.lisaa(1,1); 
    fail("PelaajanPelit: 48 Did not throw OmaException");
    } catch(OmaException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}