package tiedot;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tiedot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.04.04 15:31:44 // Generated by ComTest
 *
 */
public class IntKenttaTest {



  // Generated by ComTest BEGIN
  /** testAsetaArvo32 */
  @Test
  public void testAsetaArvo32() {    // IntKentta: 32
    IntKentta kentta = new IntKentta("julkaisuvuosi"); 
    assertEquals("From: IntKentta line: 34", null, kentta.asetaArvo("1512")); 
    assertEquals("From: IntKentta line: 35", 1512, kentta.getArvo()); 
    assertEquals("From: IntKentta line: 36", "Virhe: For input string: \"KiviJaKeppi\"", kentta.asetaArvo("KiviJaKeppi")); 
    assertEquals("From: IntKentta line: 37", 1512, kentta.getArvo()); 
  } // Generated by ComTest END
}