package tiedot;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tiedot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.04.04 15:14:41 // Generated by ComTest
 *
 */
public class JonoKenttaTest {



  // Generated by ComTest BEGIN
  /** testJonoKentta16 */
  @Test
  public void testJonoKentta16() {    // JonoKentta: 16
    JonoKentta jono = new JonoKentta("nimi"); 
    assertEquals("From: JonoKentta line: 18", "", jono.getArvo()); 
    assertEquals("From: JonoKentta line: 19", "nimi", jono.getTieto()); 
  } // Generated by ComTest END
}