package tiedot;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tiedot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.04.04 16:12:15 // Generated by ComTest
 *
 */
public class LautapeliTest {



  // Generated by ComTest BEGIN
  /** testParse61 */
  @Test
  public void testParse61() {    // Lautapeli: 61
    Lautapeli Caylus = new Lautapeli("0|Caylus|strategia|2005|2-5|60-150|Olematon|12"); 
    assertEquals("From: Lautapeli line: 63", 0, Caylus.getID()); 
    assertEquals("From: Lautapeli line: 64", "Caylus", Caylus.anna(1)); 
    assertEquals("From: Lautapeli line: 65", "2005", Caylus.anna(3)); 
    assertEquals("From: Lautapeli line: 66", "12", Caylus.anna(7)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTiedostoMuotoon89 */
  @Test
  public void testTiedostoMuotoon89() {    // Lautapeli: 89
    Lautapeli Caylus = new Lautapeli("0|Caylus|strategia|2005|2-5|60-150|Olematon|12"); 
    assertEquals("From: Lautapeli line: 91", "0|Caylus|strategia|2005|2-5|60-150|Olematon|12", Caylus.tiedostoMuotoon()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi182 */
  @Test
  public void testRekisteroi182() {    // Lautapeli: 182
    Lautapeli peli1 = new Lautapeli(); 
    peli1.rekisteroi(); 
    Lautapeli peli2 = new Lautapeli(); 
    peli2.rekisteroi(); 
    int n = peli1.getID(); 
    int m = peli2.getID(); 
    assertEquals("From: Lautapeli line: 191", m-1, n); 
  } // Generated by ComTest END
}