package tiedot;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tiedot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.03.30 17:29:38 // Generated by ComTest
 *
 */
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testParse39 */
  @Test
  public void testParse39() {    // Pelaaja: 39
    Pelaaja Pate = new Pelaaja("0|Pate Pelaaja"); 
    assertEquals("From: Pelaaja line: 41", 0, Pate.getID()); 
    assertEquals("From: Pelaaja line: 42", "Pate Pelaaja", Pate.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi84 */
  @Test
  public void testRekisteroi84() {    // Pelaaja: 84
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.rekisteroi(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.rekisteroi(); 
    int n = pelaaja1.getID(); 
    int m = pelaaja2.getID(); 
    assertEquals("From: Pelaaja line: 93", m-1, n); 
  } // Generated by ComTest END
}