package tiedot;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tiedot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.04.15 20:49:01 // Generated by ComTest
 *
 */
public class TapahtumaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi83 */
  @Test
  public void testRekisteroi83() {    // Tapahtuma: 83
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.rekisteroi(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.rekisteroi(); 
    int n = pelaaja1.getID(); 
    int m = pelaaja2.getID(); 
    assertEquals("From: Tapahtuma line: 92", m-1, n); 
  } // Generated by ComTest END
}