package lautapelilistaus;
// Generated by ComTest BEGIN
import lautapelilistaus.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

import rekisterit.*;
import tiedot.*;

/**
 * Test class made by ComTest
 * @version 2012.04.15 20:51:33 // Generated by ComTest
 *
 */
public class LautapelilistausTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa33 
   * @throws OmaException when error
   */
  @Test
  public void testLisaa33() throws OmaException {    // Lautapelilistaus: 33
    Lautapelit lautapelit = new Lautapelit(); 
    Lautapeli Caylus1 = new Lautapeli(); 
    Lautapeli Caylus2 = new Lautapeli(); 
    Lautapeli Caylus3 = new Lautapeli(); 
    Lautapeli Caylus4 = new Lautapeli(); 
    Lautapeli Caylus5 = new Lautapeli(); 
    Lautapeli Caylus6 = new Lautapeli(); 
    assertEquals("From: Lautapelilistaus line: 43", 0, lautapelit.getLukumaara()); 
    Caylus1.rekisteroi(); 
    Caylus2.rekisteroi(); 
    Caylus3.rekisteroi(); 
    Caylus4.rekisteroi(); 
    Caylus5.rekisteroi(); 
    Caylus6.rekisteroi(); 
    Caylus1.vastaaPeli(); 
    Caylus2.vastaaPeli(); 
    Caylus3.vastaaPeli(); 
    Caylus4.vastaaPeli(); 
    Caylus5.vastaaPeli(); 
    Caylus6.vastaaPeli(); 
    lautapelit.lisaa(Caylus1); assertEquals("From: Lautapelilistaus line: 59", 1, lautapelit.getLukumaara()); 
    lautapelit.lisaa(Caylus2); assertEquals("From: Lautapelilistaus line: 60", 2, lautapelit.getLukumaara()); 
    try {
    lautapelit.lisaa(Caylus1); assertEquals("From: Lautapelilistaus line: 61", 2, lautapelit.getLukumaara()); 
    fail("Lautapelilistaus: 61 Did not throw OmaException");
    } catch(OmaException _e_){ _e_.getMessage(); }
    assertEquals("From: Lautapelilistaus line: 62", Caylus1, lautapelit.anna(1)); 
    assertEquals("From: Lautapelilistaus line: 63", Caylus2, lautapelit.anna(2)); 
    lautapelit.lisaa(Caylus3); 
    lautapelit.lisaa(Caylus4); 
    lautapelit.lisaa(Caylus6); 
    lautapelit.lisaa(Caylus5); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa112 
   * @throws OmaException when error
   */
  @Test
  public void testLisaa112() throws OmaException {    // Lautapelilistaus: 112
    Pelaajat Pelaajat = new Pelaajat(); 
    Pelaaja Pelaaja1 = new Pelaaja(); 
    Pelaaja Pelaaja2 = new Pelaaja(); 
    Pelaaja Pelaaja3 = new Pelaaja(); 
    assertEquals("From: Lautapelilistaus line: 119", 0, Pelaajat.getLukumaara()); 
    Pelaaja1.rekisteroi(); 
    Pelaaja2.rekisteroi(); 
    Pelaaja1.vastaaPelaaja(); 
    Pelaaja2.vastaaPelaaja(); 
    Pelaajat.lisaa(Pelaaja1); assertEquals("From: Lautapelilistaus line: 124", 1, Pelaajat.getLukumaara()); 
    Pelaajat.lisaa(Pelaaja2); assertEquals("From: Lautapelilistaus line: 125", 2, Pelaajat.getLukumaara()); 
    try {
    Pelaajat.lisaa(Pelaaja1); assertEquals("From: Lautapelilistaus line: 126", 2, Pelaajat.getLukumaara()); 
    fail("Lautapelilistaus: 126 Did not throw OmaException");
    } catch(OmaException _e_){ _e_.getMessage(); }
    assertEquals("From: Lautapelilistaus line: 127", Pelaaja1, Pelaajat.anna(1)); 
    assertEquals("From: Lautapelilistaus line: 128", Pelaaja2, Pelaajat.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa193 
   * @throws OmaException when error
   */
  @Test
  public void testLisaa193() throws OmaException {    // Lautapelilistaus: 193
    Tapahtumat Tapahtumat = new Tapahtumat(); 
    Tapahtuma tapahtuma1 = new Tapahtuma(); 
    Tapahtuma tapahtuma2 = new Tapahtuma(); 
    Tapahtuma tapahtuma3 = new Tapahtuma(); 
    assertEquals("From: Lautapelilistaus line: 200", 0, Tapahtumat.getLukumaara()); 
    tapahtuma1.rekisteroi(0); 
    tapahtuma2.rekisteroi(0); 
    tapahtuma3.rekisteroi(0); 
    tapahtuma1.vastaaTapahtuma(); 
    tapahtuma2.vastaaTapahtuma(); 
    Tapahtumat.lisaa(tapahtuma1); assertEquals("From: Lautapelilistaus line: 206", 1, Tapahtumat.getLukumaara()); 
    Tapahtumat.lisaa(tapahtuma2); assertEquals("From: Lautapelilistaus line: 207", 2, Tapahtumat.getLukumaara()); 
    try {
    Tapahtumat.lisaa(tapahtuma1); 
    fail("Lautapelilistaus: 208 Did not throw OmaException");
    } catch(OmaException _e_){ _e_.getMessage(); }
    assertEquals("From: Lautapelilistaus line: 209", tapahtuma1, Tapahtumat.anna(1)); 
    assertEquals("From: Lautapelilistaus line: 210", tapahtuma2, Tapahtumat.anna(2)); 
  } // Generated by ComTest END
}